/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vertxtutorial

import io.vertx.core.Vertx
import io.vertx.tutorial.HttpVerticle

fun main(args: Array<String>) {
   Vertx.vertx().deployVerticle( HttpVerticle());
}
